server {
    listen 80;
    server_name odoolab.site www.odoolab.site;

    # Proxy pass vers votre conteneur Docker Odoo
    location / {
        proxy_pass http://127.0.0.1:8077; 
        # Adapter si votre conteneur écoute sur un autre port
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
